# Generated by Django 5.2.3 on 2025-10-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(default='product_images/default.jpg', help_text="Path in B2 bucket, e.g. 'product_images/default.jpg'", max_length=500),
        ),
    ]
